# Generated by Django 2.0.6 on 2018-06-06 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djpaste.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasteObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=8, null=True, unique=True)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(default=djpaste.models.expiration_date_default)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PasteObject',
                'verbose_name_plural': 'PasteObjects',
            },
        ),
        migrations.CreateModel(
            name='UsedUrlKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=8, null=True, unique=True)),
            ],
        ),
    ]
