# Generated by Django 2.0.6 on 2018-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaste', '0002_auto_20180608_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteobject',
            name='paste_name',
            field=models.CharField(default='Untitled', max_length=25),
        ),
        migrations.AddField(
            model_name='pasteobject',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasteobject',
            name='syntax_highlighting',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
